# .readthedocs.yml
#
# https://docs.readthedocs.io/en/stable/config-file/v2.html
#
# https://github.com/readthedocs/readthedocs.org/issues/4912#issuecomment-664002569

version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

# Python 3.9?
# https://docs.readthedocs.io/en/stable/config-file/v2.html#build-beta-specification
# https://github.com/readthedocs/readthedocs.org/issues/7554
python:
  install:
  - requirements: docs/requirements.txt

submodules:
  include: all
  recursive: true