# .readthedocs.yml
#
# https://docs.readthedocs.io/en/stable/config-file/v2.html
#
# https://github.com/readthedocs/readthedocs.org/issues/4912#issuecomment-664002569

version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  commands:
    - python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
    - pwd
    - ls -l
    - (cd docs/source && python -m sphinx -j auto -T -b html -d $READTHEDOCS_OUTPUT/html -D language=en .)

    # - python -m pip install --upgrade --no-cache-dir pip setuptools
#python:
#  install:
#    - requirements: docs/requirements.txt

submodules:
  # include: all
  recursive: false
