# .readthedocs.yml
#
# https://docs.readthedocs.io/en/stable/config-file/v2.html
#
# https://github.com/readthedocs/readthedocs.org/issues/4912#issuecomment-664002569

version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: docs/requirements.txt
  commands:
    - python -m sphinx -j -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html

submodules:
  # include: all
  recursive: false
