# .readthedocs.yml
# https://github.com/readthedocs/readthedocs.org/issues/4912#issuecomment-664002569

version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.9
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev