# .readthedocs.yml
#
# https://docs.readthedocs.io/en/stable/config-file/v2.html
#
# https://github.com/readthedocs/readthedocs.org/issues/4912#issuecomment-664002569

version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    - python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
    - pwd
    - ls -l
    - echo $READTHEDOCS_OUTPUT
    - (cd docs/source && python -m sphinx -j auto -T -b html -D language=en . $READTHEDOCS_OUTPUT/html)

submodules:
  # include: all
  recursive: false
