"""Spectra ERC4626 wrapper vault support.

**Important:** This vault is a Spectra ERC4626 Wrapper contract that wraps
rebasing tokens to make them compatible with Spectra's Principal Token (PT) and
Yield Token (YT) system.

Spectra Finance (wrapper deployer):

- `Homepage <https://www.spectra.finance/>`__
- `App <https://app.spectra.finance>`__
- `Documentation <https://docs.spectra.finance/>`__
- `Developer docs <https://dev.spectra.finance/>`__
- `Twitter <https://x.com/spectra_finance>`__
- `GitHub <https://github.com/perspectivefi>`__

Spectra is an interest rate derivatives protocol that splits ERC-4626 compliant
interest-bearing tokens into Principal Tokens (PT) and Yield Tokens (YT). These
wrapper contracts make various rebasing tokens compatible with Spectra's system
across multiple chains.

Currently supported wrappers:

- sw-WUSDN on Ethereum (wraps WUSDN from SmarDex)
- sw-earn on Monad (generic rebasing token wrapper)

Fee structure:

- Spectra wrapper: No additional fees
- Spectra yield fees: 3% on accrued yield from Yield Tokens (YT)

Audits:

Spectra:

- `Code4rena (March-April 2024) <https://code4rena.com/reports/2024-02-spectra>`__
- `Pashov Audit Group (March 2024) <https://github.com/pashov/audits/blob/master/team/pdf/Spectra-security-review.pdf>`__

Example vaults:

- `sw-WUSDN on Ethereum <https://etherscan.io/address/0x06a491e3efee37eb191d0434f54be6e42509f9d3>`__
- `sw-earn on Monad <https://monadscan.com/address/0x28e60b466a075cecef930d29f7f1b0facf48f950>`__
"""

import datetime
import logging

from eth_typing import BlockIdentifier

from eth_defi.erc_4626.vault import ERC4626Vault

logger = logging.getLogger(__name__)


#: Custom names for specific Spectra wrapper vaults by address
SPECTRA_VAULT_NAMES: dict[str, str] = {
    "0x06a491e3efee37eb191d0434f54be6e42509f9d3": "USDN Wrapper",
    "0x28e60b466a075cecef930d29f7f1b0facf48f950": "Staked USR Wrapper",
}


class SpectraERC4626WrapperVault(ERC4626Vault):
    """Spectra ERC4626 wrapper vault support.

    This is a wrapper contract deployed by Spectra Finance that wraps various
    rebasing tokens to make them compatible with Spectra's yield tokenisation system.

    **Note:** This is NOT a core Spectra yield tokenisation vault. It is simply
    an ERC-4626 wrapper that enables rebasing tokens to be used within Spectra's
    PT/YT system.

    The wrapper itself does not charge fees. Yield is generated by the underlying
    token's mechanism.

    - `Spectra Finance <https://www.spectra.finance/>`__
    - `Spectra docs <https://docs.spectra.finance/>`__
    """

    @property
    def name(self) -> str:
        """Return a human-readable name for this vault.

        Uses custom names for known vaults, falls back to on-chain token name.
        """
        custom_name = SPECTRA_VAULT_NAMES.get(self.vault_address.lower())
        if custom_name:
            return custom_name
        return super().name

    def has_custom_fees(self) -> bool:
        """Spectra ERC4626 wrapper does not have custom deposit/withdrawal fees.

        The wrapper is a pass-through to the underlying token.
        """
        return False

    def get_management_fee(self, block_identifier: BlockIdentifier) -> float:
        """Get the management fee.

        The Spectra wrapper does not charge management fees.

        :return:
            0.0 as there are no management fees
        """
        return 0.0

    def get_performance_fee(self, block_identifier: BlockIdentifier) -> float | None:
        """Get the performance fee.

        The Spectra wrapper does not charge performance fees directly.
        Spectra's 3% yield fee applies to Yield Tokens (YT), not to this wrapper.

        :return:
            0.0 as there are no performance fees on the wrapper
        """
        return 0.0

    def get_estimated_lock_up(self) -> datetime.timedelta | None:
        """Get the estimated lock-up period.

        There is no lock-up period for the Spectra wrapper.

        :return:
            Zero timedelta as there is no lock-up
        """
        return datetime.timedelta(0)

    def get_link(self, referral: str | None = None) -> str:
        """Get the vault's web UI link.

        Links to the Spectra app where users can interact with
        wrapped token positions.
        """
        return "https://app.spectra.finance"
