"""Spectra USDN Wrapper vault support.

**Important:** This vault is a Spectra ERC4626 Wrapper contract that wraps WUSDN,
not a core Spectra yield tokenisation vault. It makes WUSDN compatible with
Spectra's Principal Token (PT) and Yield Token (YT) system.

Wrapper chain: sw-WUSDN (Spectra) -> WUSDN (SmarDex) -> USDN (SmarDex)

Spectra Finance (wrapper deployer):

- `Homepage <https://www.spectra.finance/>`__
- `App <https://app.spectra.finance>`__
- `Documentation <https://docs.spectra.finance/>`__
- `Developer docs <https://dev.spectra.finance/>`__
- `Twitter <https://x.com/spectra_finance>`__
- `GitHub <https://github.com/perspectivefi>`__

Spectra is an interest rate derivatives protocol that splits ERC-4626 compliant
interest-bearing tokens into Principal Tokens (PT) and Yield Tokens (YT). This
specific wrapper contract makes WUSDN compatible with Spectra's system.

USDN / SmarDex (underlying protocol):

- `Homepage <https://smardex.io/>`__
- `USDN app <https://smardex.io/usdn>`__
- `Documentation <https://docs.smardex.io/ultimate-synthetic-delta-neutral>`__
- `Twitter <https://x.com/SmarDex>`__

USDN is a decentralised synthetic US dollar from SmarDex that uses a delta-neutral
strategy to maintain its ~$1 peg while generating yield from funding rates and
wstETH staking rewards. WUSDN is the non-rebasing wrapper (value increases instead
of balance), similar to wstETH vs stETH.

Example vault:

- `sw-WUSDN on Ethereum <https://etherscan.io/address/0x06a491e3efee37eb191d0434f54be6e42509f9d3>`__

Fee structure:

- Spectra wrapper: No additional fees
- Spectra yield fees: 3% on accrued yield from Yield Tokens (YT)
- USDN: Yield from funding rates and wstETH staking (no explicit deposit/withdrawal fees)

Audits:

Spectra:

- `Code4rena (March-April 2024) <https://code4rena.com/reports/2024-02-spectra>`__
- `Pashov Audit Group (March 2024) <https://github.com/pashov/audits/blob/master/team/pdf/Spectra-security-review.pdf>`__

USDN/SmarDex:

- `Guardian Audits (December 2024) <https://github.com/GuardianAudits/Audits/blob/main/Smardex/12-18-2024_Smardex_USDN.pdf>`__
- `Bailsec USDN audit <https://github.com/bailsec/BailSec/blob/main/Bailsec%20-%20Smardex%20USDN%20-%20Final%20Report.pdf>`__
"""

import datetime
import logging

from eth_typing import BlockIdentifier

from eth_defi.erc_4626.vault import ERC4626Vault

logger = logging.getLogger(__name__)


class SpectraUSDNWrapperVault(ERC4626Vault):
    """Spectra ERC4626 wrapper for WUSDN support.

    This is a wrapper contract deployed by Spectra Finance that wraps WUSDN
    (Wrapped Ultimate Synthetic Delta Neutral) from SmarDex to make it compatible
    with Spectra's yield tokenisation system.

    **Note:** This is NOT a core Spectra yield tokenisation vault. It is simply
    an ERC-4626 wrapper that enables WUSDN to be used within Spectra's PT/YT system.

    The wrapper itself does not charge fees. Yield is generated by the underlying
    USDN protocol through:

    - Funding rates from leveraged long traders
    - wstETH staking rewards

    - `Spectra Finance <https://www.spectra.finance/>`__
    - `SmarDex USDN <https://smardex.io/usdn>`__
    - `Spectra docs <https://docs.spectra.finance/>`__
    - `USDN docs <https://docs.smardex.io/ultimate-synthetic-delta-neutral>`__
    """

    @property
    def name(self) -> str:
        """Return a human-readable name for this vault type.

        Overrides the default which returns the on-chain token name.
        """
        return "USDN Wrapper"

    def has_custom_fees(self) -> bool:
        """Spectra USDN wrapper does not have custom deposit/withdrawal fees.

        The wrapper is a pass-through to the underlying WUSDN token.
        """
        return False

    def get_management_fee(self, block_identifier: BlockIdentifier) -> float:
        """Get the management fee.

        The Spectra wrapper does not charge management fees.

        :return:
            0.0 as there are no management fees
        """
        return 0.0

    def get_performance_fee(self, block_identifier: BlockIdentifier) -> float | None:
        """Get the performance fee.

        The Spectra wrapper does not charge performance fees directly.
        Spectra's 3% yield fee applies to Yield Tokens (YT), not to this wrapper.

        :return:
            0.0 as there are no performance fees on the wrapper
        """
        return 0.0

    def get_estimated_lock_up(self) -> datetime.timedelta | None:
        """Get the estimated lock-up period.

        There is no lock-up period for the Spectra wrapper.

        :return:
            Zero timedelta as there is no lock-up
        """
        return datetime.timedelta(0)

    def get_link(self, referral: str | None = None) -> str:
        """Get the vault's web UI link.

        Links to the Spectra app where users can interact with
        wrapped USDN positions.
        """
        return "https://app.spectra.finance"
