"""Test D2 Finance vault notes."""

from eth_defi.erc_4626.core import ERC4626Feature
from eth_defi.erc_4626.scan import _normalise_scan_note
from eth_defi.erc_4626.vault_protocol.d2.vault import (
    D2_TEXAS_HEDGE_ADDRESS,
    D2_VAULT_ADDRESSES,
    D2_VAULT_LINK_MATRIX,
    D2Vault,
)
from eth_defi.vault.base import VaultSpec
from eth_defi.vault.flag import SUBVAULT, VaultFlag, get_vault_special_flags, is_flagged_vault


def make_d2_vault(address: str) -> D2Vault:
    """Create a D2 vault adapter for note tests.

    These tests only exercise metadata generated by the adapter and do not
    perform JSON-RPC reads.
    """

    return D2Vault(
        web3=None,
        spec=VaultSpec(chain_id=42161, vault_address=address),
        features={ERC4626Feature.d2_like},
    )


def test_d2_protocol_vault_note_is_not_bad_flag() -> None:
    """D2 protocol notes are descriptive and do not flag the vault."""
    address = "0x75288264fdfea8ce68e6d852696ab1ce2f3e5004"
    vault = make_d2_vault(address)
    note = vault.get_notes()

    assert note is not None
    assert "D2 Finance strategy vault" in note
    assert "**Summary:**" in note
    assert "[D2 strategy page](https://d2.finance/strategies/0x75288264fdfea8ce68e6d852696ab1ce2f3e5004)" in note
    assert "[D2 strategy article](https://medium.com/@D2.Finance/hype-strategy-faq-654bc8d0efc9)" in note
    assert get_vault_special_flags(address) == set()
    assert not is_flagged_vault(address)


def test_d2_vault_note_handles_checksum_address() -> None:
    """D2 address notes are formatted case-insensitively."""
    vault = make_d2_vault("0x75288264FDFEA8ce68e6D852696aB1cE2f3E5004")
    note = vault.get_notes()

    assert note is not None
    assert "[D2 strategy page](https://d2.finance/strategies/0x75288264fdfea8ce68e6d852696ab1ce2f3e5004)" in note


def test_d2_vault_link_matrix_covers_every_known_vault() -> None:
    """D2 vault links resolve to their native D2 Finance strategy page."""
    assert set(D2_VAULT_LINK_MATRIX) == D2_VAULT_ADDRESSES

    for address, expected_link in D2_VAULT_LINK_MATRIX.items():
        assert make_d2_vault(address).get_link() == expected_link

    assert make_d2_vault(D2_TEXAS_HEDGE_ADDRESS).get_link() == "https://d2.finance/strategies/0x208f63a7f60c319597c05fa5ec67fde41839bad6"


def test_d2_unknown_protocol_vault_gets_generic_note() -> None:
    """D2 adapter notes work before an address is in the static reference set."""
    address = "0x000000000000000000000000000000000000d2d2"
    vault = make_d2_vault(address)
    note = vault.get_notes()

    assert address not in D2_VAULT_ADDRESSES
    assert note is not None
    assert "D2 Finance strategy vault" in note
    assert "[D2 strategy page](https://d2.finance/strategies/0x000000000000000000000000000000000000d2d2)" in note
    assert not is_flagged_vault(address)


def test_d2_texas_hedge_vault_note_is_not_bad_flag() -> None:
    """D2 texasHedge note is descriptive and does not flag the vault."""
    vault = make_d2_vault(D2_TEXAS_HEDGE_ADDRESS)
    note = vault.get_notes()

    assert note is not None
    assert "D2 Finance texasHedge (TXHEDGE)" in note
    assert "**Summary:**" in note
    assert "HyperEVM USDC tactical strategy vault" in note
    assert "[Texas Hedge Epoch 2 blog post](https://medium.com/@D2.Finance/texas-hedge-epoch-2-elon-takes-us-to-space-x-fec66a354ad3)" in note
    assert "[D2 strategy page](https://d2.finance/strategies/0x208f63a7f60c319597c05fa5ec67fde41839bad6)" in note
    assert "not a market-neutral yield product" in note
    assert not is_flagged_vault(D2_TEXAS_HEDGE_ADDRESS)


def test_d2_api_only_vault_note_is_not_bad_flag() -> None:
    """D2 API-only address notes are descriptive and do not flag the vault."""
    address = "0xf650ba4303ce164e1f6b215d4cbb5e212d307056"
    vault = make_d2_vault(address)
    note = vault.get_notes()

    assert address in D2_VAULT_ADDRESSES
    assert note is not None
    assert "**Summary:**" in note
    assert "[D2 strategy page](https://d2.finance/strategies/0xf650ba4303ce164e1f6b215d4cbb5e212d307056)" in note
    assert "[D2 strategy article](https://medium.com/@D2.Finance/hypereuler-x-pol-pol-is-here-is-time-to-supercharge-your-bera-4dfaa8805d23)" in note
    assert not is_flagged_vault(address)


def test_trading_strategy_only_d2_vault_note_is_not_bad_flag() -> None:
    """Trading Strategy D2-export address notes are descriptive and do not flag the vault."""
    address = "0x4ada76cc8755f62508a2df65d7fafa4fd26e76c6"
    vault = make_d2_vault(address)
    note = vault.get_notes()

    assert address in D2_VAULT_ADDRESSES
    assert note is not None
    assert "**Summary:**" in note
    assert "[D2 strategy page](https://d2.finance/strategies/0x4ada76cc8755f62508a2df65d7fafa4fd26e76c6)" in note
    assert "D2 strategy article" not in note
    assert not is_flagged_vault(address)


def test_d2_vault_note_does_not_override_bad_manual_flag() -> None:
    """D2 address notes do not mask explicit bad manual flags."""
    address = "0x64167cd42859f64cff2aa4b63c3175ccef9659dd"
    vault = make_d2_vault(address)
    note = vault.get_notes()

    assert address in D2_VAULT_ADDRESSES
    assert get_vault_special_flags(address) == {VaultFlag.subvault}
    assert is_flagged_vault(address)
    assert note == SUBVAULT


def test_scan_note_normalisation_drops_duplicate_descriptions() -> None:
    """Scan metadata notes do not duplicate exported description fields."""
    description = "Protocol supplied vault description"
    distinct_note = "D2 Finance strategy vault with authoritative source link"

    assert _normalise_scan_note(None, description, None) is None
    assert _normalise_scan_note(description, description, None) is None
    assert _normalise_scan_note(description, None, description) is None
    assert _normalise_scan_note(distinct_note, description, None) == distinct_note
