from ccxt.base.errors import ExchangeError
from ccxt.base.errors import NetworkError
from ccxt.base.errors import NotSupported
from ccxt.base.errors import AuthenticationError
from ccxt.base.errors import DDoSProtection
from ccxt.base.errors import RequestTimeout
from ccxt.base.errors import ExchangeNotAvailable
from ccxt.base.errors import InvalidAddress
from ccxt.base.errors import InvalidOrder
from ccxt.base.errors import ArgumentsRequired
from ccxt.base.errors import BadSymbol
from ccxt.base.errors import NullResponse
from ccxt.base.errors import RateLimitExceeded
from ccxt.base.errors import OperationFailed
from ccxt.base.errors import BadRequest
from ccxt.base.errors import BadResponse
from ccxt.base.errors import InvalidProxySettings
from ccxt.base.errors import UnsubscribeError

from ccxt.base.decimal_to_precision import DECIMAL_PLACES, TICK_SIZE, NO_PADDING, TRUNCATE, ROUND, ROUND_UP, ROUND_DOWN, SIGNIFICANT_DIGITS


def describe_gmx() -> dict:
    """Return the CCXT exchange description for GMX DEX.

    See CCXT documentation for `Exchange.describe() <https://docs.ccxt.com/#/?id=exchange-class>`__
    """

    timeout = 30

    return {
        "id": None,
        "name": None,
        "countries": None,
        "enableRateLimit": True,
        "rateLimit": 2000,  # milliseconds = seconds * 1000
        "timeout": timeout * 1000,  # milliseconds = seconds * 1000
        "certified": False,  # if certified by the CCXT dev team
        "pro": False,  # if it is integrated with CCXT Pro for WebSocket support
        "alias": False,  # whether self exchange is an alias to another exchange
        "dex": False,
        "has": {
            "publicAPI": True,
            "privateAPI": True,
            "CORS": None,
            "sandbox": None,
            "spot": None,
            "margin": None,
            "swap": None,
            "future": None,
            "option": None,
            "addMargin": None,
            "borrowCrossMargin": None,
            "borrowIsolatedMargin": None,
            "borrowMargin": None,
            "cancelAllOrders": None,
            "cancelAllOrdersWs": None,
            "cancelOrder": True,
            "cancelOrderWithClientOrderId": None,
            "cancelOrderWs": None,
            "cancelOrders": None,
            "cancelOrdersWithClientOrderId": None,
            "cancelOrdersWs": None,
            "closeAllPositions": None,
            "closePosition": None,
            "createDepositAddress": None,
            "createLimitBuyOrder": None,
            "createLimitBuyOrderWs": None,
            "createLimitOrder": True,
            "createLimitOrderWs": None,
            "createLimitSellOrder": None,
            "createLimitSellOrderWs": None,
            "createMarketBuyOrder": None,
            "createMarketBuyOrderWs": None,
            "createMarketBuyOrderWithCost": None,
            "createMarketBuyOrderWithCostWs": None,
            "createMarketOrder": True,
            "createMarketOrderWs": True,
            "createMarketOrderWithCost": None,
            "createMarketOrderWithCostWs": None,
            "createMarketSellOrder": None,
            "createMarketSellOrderWs": None,
            "createMarketSellOrderWithCost": None,
            "createMarketSellOrderWithCostWs": None,
            "createOrder": True,
            "createOrderWs": None,
            "createOrders": None,
            "createOrderWithTakeProfitAndStopLoss": None,
            "createOrderWithTakeProfitAndStopLossWs": None,
            "createPostOnlyOrder": None,
            "createPostOnlyOrderWs": None,
            "createReduceOnlyOrder": None,
            "createReduceOnlyOrderWs": None,
            "createStopLimitOrder": None,
            "createStopLimitOrderWs": None,
            "createStopLossOrder": None,
            "createStopLossOrderWs": None,
            "createStopMarketOrder": None,
            "createStopMarketOrderWs": None,
            "createStopOrder": None,
            "createStopOrderWs": None,
            "createTakeProfitOrder": None,
            "createTakeProfitOrderWs": None,
            "createTrailingAmountOrder": None,
            "createTrailingAmountOrderWs": None,
            "createTrailingPercentOrder": None,
            "createTrailingPercentOrderWs": None,
            "createTriggerOrder": None,
            "createTriggerOrderWs": None,
            "deposit": None,
            "editOrder": "emulated",
            "editOrderWithClientOrderId": None,
            "editOrders": None,
            "editOrderWs": None,
            "fetchAccounts": None,
            "fetchBalance": True,
            "fetchBalanceWs": None,
            "fetchBidsAsks": None,
            "fetchBorrowInterest": None,
            "fetchBorrowRate": None,
            "fetchBorrowRateHistories": None,
            "fetchBorrowRateHistory": None,
            "fetchBorrowRates": None,
            "fetchBorrowRatesPerSymbol": None,
            "fetchCanceledAndClosedOrders": None,
            "fetchCanceledOrders": None,
            "fetchClosedOrder": None,
            "fetchClosedOrders": None,
            "fetchClosedOrdersWs": None,
            "fetchConvertCurrencies": None,
            "fetchConvertQuote": None,
            "fetchConvertTrade": None,
            "fetchConvertTradeHistory": None,
            "fetchCrossBorrowRate": None,
            "fetchCrossBorrowRates": None,
            "fetchCurrencies": "emulated",
            "fetchCurrenciesWs": "emulated",
            "fetchDeposit": None,
            "fetchDepositAddress": None,
            "fetchDepositAddresses": None,
            "fetchDepositAddressesByNetwork": None,
            "fetchDeposits": None,
            "fetchDepositsWithdrawals": None,
            "fetchDepositsWs": None,
            "fetchDepositWithdrawFee": None,
            "fetchDepositWithdrawFees": None,
            "fetchFundingHistory": None,
            "fetchFundingRate": None,
            "fetchFundingRateHistory": None,
            "fetchFundingInterval": None,
            "fetchFundingIntervals": None,
            "fetchFundingRates": None,
            "fetchGreeks": None,
            "fetchIndexOHLCV": None,
            "fetchIsolatedBorrowRate": None,
            "fetchIsolatedBorrowRates": None,
            "fetchMarginAdjustmentHistory": None,
            "fetchIsolatedPositions": None,
            "fetchL2OrderBook": True,
            "fetchL3OrderBook": None,
            "fetchLastPrices": None,
            "fetchLedger": None,
            "fetchLedgerEntry": None,
            "fetchLeverage": None,
            "fetchLeverages": None,
            "fetchLeverageTiers": None,
            "fetchLiquidations": None,
            "fetchLongShortRatio": None,
            "fetchLongShortRatioHistory": None,
            "fetchMarginMode": None,
            "fetchMarginModes": None,
            "fetchMarketLeverageTiers": None,
            "fetchMarkets": True,
            "fetchMarketsWs": None,
            "fetchMarkOHLCV": None,
            "fetchMyLiquidations": None,
            "fetchMySettlementHistory": None,
            "fetchMyTrades": None,
            "fetchMyTradesWs": None,
            "fetchOHLCV": None,
            "fetchOHLCVWs": None,
            "fetchOpenInterest": None,
            "fetchOpenInterests": None,
            "fetchOpenInterestHistory": None,
            "fetchOpenOrder": None,
            "fetchOpenOrders": None,
            "fetchOpenOrdersWs": None,
            "fetchOption": None,
            "fetchOptionChain": None,
            "fetchOrder": None,
            "fetchOrderWithClientOrderId": None,
            "fetchOrderBook": True,
            "fetchOrderBooks": None,
            "fetchOrderBookWs": None,
            "fetchOrders": None,
            "fetchOrdersByStatus": None,
            "fetchOrdersWs": None,
            "fetchOrderTrades": None,
            "fetchOrderWs": None,
            "fetchPosition": None,
            "fetchPositionHistory": None,
            "fetchPositionsHistory": None,
            "fetchPositionWs": None,
            "fetchPositionMode": None,
            "fetchPositions": None,
            "fetchPositionsWs": None,
            "fetchPositionsForSymbol": None,
            "fetchPositionsForSymbolWs": None,
            "fetchPositionsRisk": None,
            "fetchPremiumIndexOHLCV": None,
            "fetchSettlementHistory": None,
            "fetchStatus": None,
            "fetchTicker": True,
            "fetchTickerWs": None,
            "fetchTickers": None,
            "fetchMarkPrices": None,
            "fetchTickersWs": None,
            "fetchTime": None,
            "fetchTrades": True,
            "fetchTradesWs": None,
            "fetchTradingFee": None,
            "fetchTradingFees": None,
            "fetchTradingFeesWs": None,
            "fetchTradingLimits": None,
            "fetchTransactionFee": None,
            "fetchTransactionFees": None,
            "fetchTransactions": None,
            "fetchTransfer": None,
            "fetchTransfers": None,
            "fetchUnderlyingAssets": None,
            "fetchVolatilityHistory": None,
            "fetchWithdrawAddresses": None,
            "fetchWithdrawal": None,
            "fetchWithdrawals": None,
            "fetchWithdrawalsWs": None,
            "fetchWithdrawalWhitelist": None,
            "reduceMargin": None,
            "repayCrossMargin": None,
            "repayIsolatedMargin": None,
            "setLeverage": None,
            "setMargin": None,
            "setMarginMode": None,
            "setPositionMode": None,
            "signIn": None,
            "transfer": None,
            "watchBalance": None,
            "watchMyTrades": None,
            "watchOHLCV": None,
            "watchOHLCVForSymbols": None,
            "watchOrderBook": None,
            "watchBidsAsks": None,
            "watchOrderBookForSymbols": None,
            "watchOrders": None,
            "watchOrdersForSymbols": None,
            "watchPosition": None,
            "watchPositions": None,
            "watchStatus": None,
            "watchTicker": None,
            "watchTickers": None,
            "watchTrades": None,
            "watchTradesForSymbols": None,
            "watchLiquidations": None,
            "watchLiquidationsForSymbols": None,
            "watchMyLiquidations": None,
            "unWatchOrders": None,
            "unWatchTrades": None,
            "unWatchTradesForSymbols": None,
            "unWatchOHLCVForSymbols": None,
            "unWatchOrderBookForSymbols": None,
            "unWatchPositions": None,
            "unWatchOrderBook": None,
            "unWatchTickers": None,
            "unWatchMyTrades": None,
            "unWatchTicker": None,
            "unWatchOHLCV": None,
            "watchMyLiquidationsForSymbols": None,
            "withdraw": None,
            "ws": None,
        },
        "urls": {
            "logo": None,
            "api": None,
            "www": None,
            "doc": None,
            "fees": None,
        },
        "api": None,
        "requiredCredentials": {
            "apiKey": True,
            "secret": True,
            "uid": False,
            "accountId": False,
            "login": False,
            "password": False,
            "twofa": False,  # 2-factor authentication(one-time password key)
            "privateKey": False,  # a "0x"-prefixed hexstring private key for a wallet
            "walletAddress": False,  # the wallet address "0x"-prefixed hexstring
            "token": False,  # reserved for HTTP auth in some cases
        },
        "markets": None,  # to be filled manually or by fetchMarkets
        "currencies": {},  # to be filled manually or by fetchMarkets
        "timeframes": None,  # redefine if the exchange has.fetchOHLCV
        "fees": {
            "trading": {
                "tierBased": None,
                "percentage": None,
                "taker": None,
                "maker": None,
            },
            "funding": {
                "tierBased": None,
                "percentage": None,
                "withdraw": {},
                "deposit": {},
            },
        },
        "status": {
            "status": "ok",
            "updated": None,
            "eta": None,
            "url": None,
        },
        "exceptions": None,
        "httpExceptions": {
            "422": ExchangeError,
            "418": DDoSProtection,
            "429": RateLimitExceeded,
            "404": ExchangeNotAvailable,
            "409": ExchangeNotAvailable,
            "410": ExchangeNotAvailable,
            "451": ExchangeNotAvailable,
            "500": ExchangeNotAvailable,
            "501": ExchangeNotAvailable,
            "502": ExchangeNotAvailable,
            "520": ExchangeNotAvailable,
            "521": ExchangeNotAvailable,
            "522": ExchangeNotAvailable,
            "525": ExchangeNotAvailable,
            "526": ExchangeNotAvailable,
            "400": ExchangeNotAvailable,
            "403": ExchangeNotAvailable,
            "405": ExchangeNotAvailable,
            "503": ExchangeNotAvailable,
            "530": ExchangeNotAvailable,
            "408": RequestTimeout,
            "504": RequestTimeout,
            "401": AuthenticationError,
            "407": AuthenticationError,
            "511": AuthenticationError,
        },
        "commonCurrencies": {
            "XBT": "BTC",
            "BCHSV": "BSV",
        },
        "precisionMode": TICK_SIZE,
        "paddingMode": NO_PADDING,
        "limits": {
            "leverage": {"min": None, "max": None},
            "amount": {"min": None, "max": None},
            "price": {"min": None, "max": None},
            "cost": {"min": None, "max": None},
        },
    }
