"""Test data integrity for Base-USDC Yield-DynaVault v3 vault on chain 8453.

Vault: Base-USDC Yield-DynaVault v3 (dynBaseUSDCv3)
Chain: 8453 (Base)
Address: 0x67b93f6676bd1911c5fae7ffa90fff5f35e14dcd
Protocol: Singularity Finance
Denomination: USDC
Link: https://singularityfinance.ai/

Fees:
    Management: None
    Performance: None
    Deposit: 0.0
    Withdrawal: 0

Generated by scripts/erc-4626/extract-test-set.py
"""

import os.path
from pathlib import Path

import pandas as pd
import pytest

from eth_defi.research.wrangle_vault_prices import remove_inactive_lead_time

CHAIN_ID = 8453
VAULT_ADDRESS = "0x67b93f6676bd1911c5fae7ffa90fff5f35e14dcd"


@pytest.fixture(scope="module")
def price_df() -> pd.DataFrame:
    """Load extracted raw price data for this vault."""
    path = Path(os.path.dirname(__file__)) / "vault-base-usdc-yield-dynavault-v3-prices-1h.parquet"
    return pd.read_parquet(path)


def test_remove_inactive_lead_time(price_df: pd.DataFrame):
    """Check eliminating the empty lead period of data.

    - Verify that remove_inactive_lead_time() correctly strips the initial
      period where total_supply is constant (no deposits/redemptions yet)
    - Raw data needs 'id' column and timestamp index for remove_inactive_lead_time()
    """
    df = price_df.copy()
    df["id"] = df["chain"].astype(str) + "-" + df["address"].astype(str)
    if "timestamp" in df.columns:
        df = df.set_index("timestamp")
    original_len = len(df)
    cleaned = remove_inactive_lead_time(df, logger=lambda *args: None)
    # After removing inactive lead time, we should have equal or fewer rows
    assert len(cleaned) <= original_len
    # The cleaned data should still have valid share prices
