name: Lint

on:
  push:
    branches: [master]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    branches: [master]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.14

      - name: Cache Poetry & Pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: poetry-lint-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-lint-${{ runner.os }}-

      - name: Install poetry
        run: pipx install "poetry>=2.3" --python "${{ env.PYTHON_PATH }}"

      - name: Install lint dependencies
        run: |
          poetry install --no-root

      - name: Ruff lint check
        run: |
          poetry run ruff format --check --diff
