name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  ruff:
    if: github.event.pull_request.draft == false || github.event_name == 'push'
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install "poetry>=2.3"

      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: "poetry"
          cache-dependency-path: "**/pyproject.toml"

      - name: Install dependencies
        run: poetry install --no-root --only dev

      - name: Ruff format check
        run: poetry run ruff format --check --diff
